name: kaspion
version: "1.0"
profile: kaspion
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  kaspion:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
